package at.db.starlink.watchtower.model.starlink.dish;

public enum DisablementCode {
    UNKNOWN, OKAY, NO_ACTIVE_ACCOUNT, TOO_FAR_FROM_SERVICE_ADDRESS, IN_OCEAN, BLOCKED_COUNTRY,
    DATA_OVERAGE_SANDBOX_POLICY, CELL_IS_DISABLED, ROAM_RESTRICTED, UNKNOWN_LOCATION, ACCOUNT_DISABLED,
    UNSUPPORTED_VERSION, MOVING_TOO_FAST_FOR_POLICY
}
